name: example
description: An example output
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  lints: ^1.0.0
